add_subdirectory(asyncappendertest)
add_subdirectory(headerfootertest)
add_subdirectory(jsonlayouttest)
add_subdirectory(dailyrollingfileappendertest)
add_subdirectory(jsontest)
add_subdirectory(log4qttest)
add_subdirectory(mainthreadappendertest)
add_subdirectory(filewatcher)
add_subdirectory(performancetest)
add_subdirectory(policytest)
add_subdirectory(propertytest)
if(BUILD_WITH_TELNET_LOGGING)
    add_subdirectory(telnetappendertest)
endif()
add_subdirectory(writerappendertest)
add_subdirectory(xmltest)
