name: CMake macOS build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: macOS - Qt ${{ matrix.qt_version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        qt_version: [6.2.4, 6.5.3, 6.8.3, 6.10.2]

    steps:
    - uses: actions/checkout@v4

    - name: Install ninja
      run: brew install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_version }}

    - name: Create Build Environment
      run: cmake -E make_directory ${{ runner.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
